# Generated by Django 4.1.5 on 2023-04-08 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MalAuto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='data',
        ),
    ]
