# Generated by Django 4.1.5 on 2023-04-08 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MalAuto', '0002_remove_reservation_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='images',
        ),
    ]
