# Generated by Django 4.1.5 on 2023-04-08 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MalAuto', '0003_remove_reservation_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='images',
            field=models.ImageField(default=1, upload_to='clients'),
            preserve_default=False,
        ),
    ]
