# Generated by Django 4.1.5 on 2023-04-08 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MalAuto', '0004_reservation_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='images',
        ),
    ]
