# Generated by Django 2.2 on 2023-04-11 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MalAuto', '0005_remove_reservation_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
